### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by i11us0ry** [r00tSe7en/JNDIMonitor#1]
系统：
Linux 10-255-1-168 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "1.8.0_292"

运行：
root@10-255-1-168:~/tool# java -jar JNDI.jar -i 0.0.0.0 -l 1389 -p 3456
[+] LDAP Server Start Listening on 1389...
[+] HTTP Server Start Listening on 3456...

访问结果：
root@10-255-1-168:~/tool# curl http://**.**.**.**:3456/api=123
curl: (52) Empty reply from server

**Comment by r00tSe7en** [comment]
@i11us0ry http://ip:port/?api=xxxxxx(长度无限制)，少了`?`号啊

**Comment by i11us0ry** [comment]
请问返回no又是啥情况呢，第一次是yes  之后就一直是no 重启也是
root@10-255-1-168:~# curl http://xx.xx.xx.xx:3456/?api=aaaa
no

**Comment by r00tSe7en** [comment]
看一下你的tmp.txt里面有没有aaaa呢，有就返回yes，没有就返回no

**Comment by i11us0ry** [comment]
有第一次的记录 后门就都没了 我的意思是为啥同样环境同样请求 就换了api的值  后面都成失败了呢

**Comment by r00tSe7en** [comment]
不知道你什么环境，我本地测试是没有问题的额

**Comment by i11us0ry** [comment]
![image](https://user-images.githubusercontent.com/34978854/145949494-0eab8623-2b5b-4f25-ac38-d7d0af0623e9.png)

你提供的示例里也有，就莫名其妙变成no了

**Comment by r00tSe7en** [comment]
文本里不存在这个字符串，返回no没问题啊，这是个就是个判断是否有ldap回连记录的接口
